/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../../common'

export interface IRewarderInterface extends utils.Interface {
    functions: {
        'connect(address)': FunctionFragment
        'onUpdate(address,address,uint256,uint256,uint256)': FunctionFragment
    }

    getFunction(nameOrSignatureOrTopic: 'connect' | 'onUpdate'): FunctionFragment

    encodeFunctionData(functionFragment: 'connect', values: [PromiseOrValue<string>]): string
    encodeFunctionData(
        functionFragment: 'onUpdate',
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
        ]
    ): string

    decodeFunctionResult(functionFragment: 'connect', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'onUpdate', data: BytesLike): Result

    events: {
        'RewarderConnected(address)': EventFragment
    }

    getEvent(nameOrSignatureOrTopic: 'RewarderConnected'): EventFragment
}

export interface RewarderConnectedEventObject {
    stakingToken: string
}
export type RewarderConnectedEvent = TypedEvent<[string], RewarderConnectedEventObject>

export type RewarderConnectedEventFilter = TypedEventFilter<RewarderConnectedEvent>

export interface IRewarder extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: IRewarderInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        connect(
            stakingToken: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        onUpdate(
            token: PromiseOrValue<string>,
            user: PromiseOrValue<string>,
            oldStake: PromiseOrValue<BigNumberish>,
            oldSupply: PromiseOrValue<BigNumberish>,
            newStake: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    onUpdate(
        token: PromiseOrValue<string>,
        user: PromiseOrValue<string>,
        oldStake: PromiseOrValue<BigNumberish>,
        oldSupply: PromiseOrValue<BigNumberish>,
        newStake: PromiseOrValue<BigNumberish>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        connect(stakingToken: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>

        onUpdate(
            token: PromiseOrValue<string>,
            user: PromiseOrValue<string>,
            oldStake: PromiseOrValue<BigNumberish>,
            oldSupply: PromiseOrValue<BigNumberish>,
            newStake: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {
        'RewarderConnected(address)'(stakingToken?: PromiseOrValue<string> | null): RewarderConnectedEventFilter
        RewarderConnected(stakingToken?: PromiseOrValue<string> | null): RewarderConnectedEventFilter
    }

    estimateGas: {
        connect(
            stakingToken: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        onUpdate(
            token: PromiseOrValue<string>,
            user: PromiseOrValue<string>,
            oldStake: PromiseOrValue<BigNumberish>,
            oldSupply: PromiseOrValue<BigNumberish>,
            newStake: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        connect(
            stakingToken: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        onUpdate(
            token: PromiseOrValue<string>,
            user: PromiseOrValue<string>,
            oldStake: PromiseOrValue<BigNumberish>,
            oldSupply: PromiseOrValue<BigNumberish>,
            newStake: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
