name: abstract-mainnet
eid: ABSTRACT_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
  usdc:
    type: oft
  usdt:
    type: oft
rewarder:
  tokens:
    eth:
      allocation:
        eth: 10000
staking:
  tokens:
    eth: true
treasurer:
  tokens:
    usdt: true
    usdc: true
