name: aurora-mainnet
eid: AURORA_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: pool
rewarder:
  tokens:
    aurora:
      allocation:
        usdc: 10000
staking:
  tokens:
    usdc: true
treasurer:
  tokens:
    usdc: true
