name: base-mainnet
eid: BASE_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
  usdc:
    type: pool
rewarder:
  tokens:
    stg:
      allocation:
        eth: 6500
        usdc: 3500
staking:
  tokens:
    eth: true
    usdc: true
treasurer:
  tokens:
    eth: true
    usdc: true
