name: bera-mainnet
eid: BERA_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
  eurc:
    type: oft
treasurer:
  tokens:
    eth: true
    usdc: true
    eurc: true
