name: cronoszkevm-mainnet
eid: CRONOSZKEVM_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: pool
  usdc:
    type: pool
treasurer:
  tokens:
    eth: true
    usdc: true
