name: edu-mainnet
eid: EDU_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: oft
treasurer:
  tokens:
    usdc: true
# deprecation
status: DEPRECATED
unwire:
  token_messaging:
  # todo first unwire from then once there are not inflight run with direction: both
    direction: from
    allowed_peers:
      - edu-mainnet
  credit_messaging:
    direction: both
    allowed_peers:
      - edu-mainnet