name: ethereum-mainnet
eid: ETHEREUM_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
  meth:
    type: pool
  metis:
    type: pool
  usdc:
    type: pool
  usdt:
    type: pool
  eurc:
    type: pool
rewarder:
  tokens:
    stg:
      allocation:
        eth: 4767
        usdc: 4100
        usdt: 1133
    eurc:
      allocation:
        eurc: 1
staking:
  tokens:
    eth: true
    usdc: true
    usdt: true
    eurc: true
treasurer:
  tokens:
    eth: true
    meth: true
    metis: true
    usdt: true
    usdc: true
    eurc: true
