name: glue-mainnet
eid: GLUE_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    eth: true
    usdt: true
    usdc: true
# deprecation
status: DEPRECATED
unwire:
  token_messaging:
    # ! disabling incoming messages only for now as part of Phase 1. It should disconnect both directions in Phase 2
    direction: to
    allowed_peers:
      - glue-mainnet
  credit_messaging:
    direction: both
    allowed_peers:
      - glue-mainnet
# TODO Taiko chain is down we need to unwire it once it is up
