name: gnosis-mainnet
eid: GNOSIS_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: pool
  usdc:
    type: pool
treasurer:
  tokens:
    eth: true
    usdc: true
unwire:
    token_messaging:
        # todo disconnect both directions on the second step
        direction: from
        allowed_peers:
            - gnosis-mainnet
    credit_messaging:
        direction: both
        allowed_peers:
            - gnosis-mainnet