name: lightlink-mainnet
eid: LIGHTLINK_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
  usdc:
    type: oft
  usdt:
    type: oft
rewarder:
  tokens:
    lle:
      allocation:
        eth: 10000
staking:
  tokens:
    eth: true
treasurer:
  tokens:
    eth: true
    usdt: true
    usdc: true
