name: mantle-mainnet
eid: MANTLE_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: pool
  meth:
    type: pool
  usdc:
    type: pool
  usdt:
    type: pool
rewarder:
  tokens:
    stg:
      allocation:
        eth: 7000
        usdc: 1500
        usdt: 1500
staking:
  tokens:
    eth: true
    usdc: true
    usdt: true
treasurer:
  tokens:
    eth: true
    meth: true
    usdt: true
    usdc: true
