name: nibiru-mainnet
eid: NIBIRU_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    eth: true
    usdt: true
    usdc: true
