name: plumephoenix-mainnet
eid: PLUMEPHOENIX_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    usdt: true
    usdc: true
