name: polygon-mainnet
eid: POLYGON_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: pool
  usdt:
    type: pool
rewarder:
  tokens:
    stg:
      allocation:
        usdc: 5959
        usdt: 4041
staking:
  tokens:
    usdc: true
    usdt: true
treasurer:
  tokens:
    usdt: true
    usdc: true
