name: rarible-mainnet
eid: RARIBLE_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    usdt: true
    usdc: true
usdc_admin: true
