name: scroll-mainnet
eid: SCROLL_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
  usdc:
    type: pool
rewarder:
  tokens:
    stg:
      allocation:
        eth: 7000
        usdc: 3000
staking:
  tokens:
    eth: true
    usdc: true
treasurer:
  tokens:
    eth: true
    usdc: true
