name: sei-mainnet
eid: SEI_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
unwired_tokens:
  usdc:
    type: pool
  usdt:
    type: pool
treasurer:
  tokens:
    eth: true