name: sei-mainnet
eid: SEI_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: pool
  usdt:
    type: pool
rewarder:
  tokens:
    sei:
      allocation:
        usdc: 5000
        usdt: 5000
staking:
  tokens:
    usdc: true
    usdt: true
treasurer:
  tokens:
    eth: true
    usdt: true
    usdc: true
