name: somnia-mainnet
eid: SOMNIA_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: oft
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    eth: true
    usdc: true
    usdt: true
