name: sonic-mainnet
eid: SONIC_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: pool
rewarder:
  tokens:
    s:
      allocation:
        usdc: 10000
staking:
  tokens:
    usdc: true
treasurer:
  tokens:
    usdc: true
