name: superposition-mainnet
eid: SUPERPOSITION_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: oft
treasurer:
  tokens:
    usdc: true
status: DEPRECATED
unwire:
    token_messaging:
    # todo: update to from once fist batch is completed and no inflight messages are pending
        direction: to
        allowed_peers:
            - superposition-mainnet
    credit_messaging:
        direction: both
        allowed_peers:
            - superposition-mainnet