name: taiko-mainnet
eid: TAIKO_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  usdc:
    type: oft
  usdt:
    type: oft
treasurer:
  tokens:
    usdt: true
    usdc: true
unwire:
    token_messaging:
        # todo disconnect both directions on the second step
        direction: to
        allowed_peers:
            - taiko-mainnet
    credit_messaging:
        direction: both
        allowed_peers:
            - taiko-mainnet