name: zkconsensys-mainnet
eid: ZKCONSENSYS_V2_MAINNET
token_messaging: true
credit_messaging: true
tokens:
  eth:
    type: native
rewarder:
  tokens:
    stg:
      allocation:
        eth: 10000
staking:
  tokens:
    eth: true
treasurer:
  tokens:
    eth: true
