/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumber, BytesLike, CallOverrides, PopulatedTransaction, Signer, utils } from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../common'

export interface IOAppComputerMapInterface extends utils.Interface {
    functions: {
        'lzMap(bytes,bytes)': FunctionFragment
    }

    getFunction(nameOrSignatureOrTopic: 'lzMap'): FunctionFragment

    encodeFunctionData(
        functionFragment: 'lzMap',
        values: [PromiseOrValue<BytesLike>, PromiseOrValue<BytesLike>]
    ): string

    decodeFunctionResult(functionFragment: 'lzMap', data: BytesLike): Result

    events: {}
}

export interface IOAppComputerMap extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: IOAppComputerMapInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        lzMap(
            _request: PromiseOrValue<BytesLike>,
            _response: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<[string]>
    }

    lzMap(
        _request: PromiseOrValue<BytesLike>,
        _response: PromiseOrValue<BytesLike>,
        overrides?: CallOverrides
    ): Promise<string>

    callStatic: {
        lzMap(
            _request: PromiseOrValue<BytesLike>,
            _response: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<string>
    }

    filters: {}

    estimateGas: {
        lzMap(
            _request: PromiseOrValue<BytesLike>,
            _response: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<BigNumber>
    }

    populateTransaction: {
        lzMap(
            _request: PromiseOrValue<BytesLike>,
            _response: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>
    }
}
