/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    PayableOverrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../common'

export interface DecompressorExtensionInterface extends utils.Interface {
    functions: {
        'MAX_DICT_LEN()': FunctionFragment
        'RESERVE_DICT_LEN()': FunctionFragment
        'decompress()': FunctionFragment
        'decompressed()': FunctionFragment
        'getData(uint256,uint256)': FunctionFragment
    }

    getFunction(
        nameOrSignatureOrTopic: 'MAX_DICT_LEN' | 'RESERVE_DICT_LEN' | 'decompress' | 'decompressed' | 'getData'
    ): FunctionFragment

    encodeFunctionData(functionFragment: 'MAX_DICT_LEN', values?: undefined): string
    encodeFunctionData(functionFragment: 'RESERVE_DICT_LEN', values?: undefined): string
    encodeFunctionData(functionFragment: 'decompress', values?: undefined): string
    encodeFunctionData(functionFragment: 'decompressed', values?: undefined): string
    encodeFunctionData(
        functionFragment: 'getData',
        values: [PromiseOrValue<BigNumberish>, PromiseOrValue<BigNumberish>]
    ): string

    decodeFunctionResult(functionFragment: 'MAX_DICT_LEN', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'RESERVE_DICT_LEN', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'decompress', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'decompressed', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'getData', data: BytesLike): Result

    events: {}
}

export interface DecompressorExtension extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: DecompressorExtensionInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        MAX_DICT_LEN(overrides?: CallOverrides): Promise<[BigNumber]>

        RESERVE_DICT_LEN(overrides?: CallOverrides): Promise<[BigNumber]>

        decompress(overrides?: PayableOverrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

        decompressed(overrides?: CallOverrides): Promise<[string] & { raw: string }>

        getData(
            begin: PromiseOrValue<BigNumberish>,
            end: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<[string[]] & { res: string[] }>
    }

    MAX_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

    RESERVE_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

    decompress(overrides?: PayableOverrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

    decompressed(overrides?: CallOverrides): Promise<string>

    getData(
        begin: PromiseOrValue<BigNumberish>,
        end: PromiseOrValue<BigNumberish>,
        overrides?: CallOverrides
    ): Promise<string[]>

    callStatic: {
        MAX_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

        RESERVE_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

        decompress(overrides?: CallOverrides): Promise<void>

        decompressed(overrides?: CallOverrides): Promise<string>

        getData(
            begin: PromiseOrValue<BigNumberish>,
            end: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<string[]>
    }

    filters: {}

    estimateGas: {
        MAX_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

        RESERVE_DICT_LEN(overrides?: CallOverrides): Promise<BigNumber>

        decompress(overrides?: PayableOverrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>

        decompressed(overrides?: CallOverrides): Promise<BigNumber>

        getData(
            begin: PromiseOrValue<BigNumberish>,
            end: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<BigNumber>
    }

    populateTransaction: {
        MAX_DICT_LEN(overrides?: CallOverrides): Promise<PopulatedTransaction>

        RESERVE_DICT_LEN(overrides?: CallOverrides): Promise<PopulatedTransaction>

        decompress(overrides?: PayableOverrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>

        decompressed(overrides?: CallOverrides): Promise<PopulatedTransaction>

        getData(
            begin: PromiseOrValue<BigNumberish>,
            end: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>
    }
}
