/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { AdminUpgradeabilityProxy } from './AdminUpgradeabilityProxy'
export type { Proxy } from './Proxy'
export type { UpgradeabilityProxy } from './UpgradeabilityProxy'
