/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result, EventFragment } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../../../../common'

export interface V2UpgraderHelperInterface extends utils.Interface {
    functions: {
        'balanceOf(address)': FunctionFragment
        'blacklister()': FunctionFragment
        'currency()': FunctionFragment
        'decimals()': FunctionFragment
        'fiatTokenOwner()': FunctionFragment
        'masterMinter()': FunctionFragment
        'name()': FunctionFragment
        'owner()': FunctionFragment
        'pauser()': FunctionFragment
        'proxy()': FunctionFragment
        'symbol()': FunctionFragment
        'tearDown()': FunctionFragment
        'transferFrom(address,address,uint256)': FunctionFragment
        'transferOwnership(address)': FunctionFragment
    }

    getFunction(
        nameOrSignatureOrTopic:
            | 'balanceOf'
            | 'blacklister'
            | 'currency'
            | 'decimals'
            | 'fiatTokenOwner'
            | 'masterMinter'
            | 'name'
            | 'owner'
            | 'pauser'
            | 'proxy'
            | 'symbol'
            | 'tearDown'
            | 'transferFrom'
            | 'transferOwnership'
    ): FunctionFragment

    encodeFunctionData(functionFragment: 'balanceOf', values: [PromiseOrValue<string>]): string
    encodeFunctionData(functionFragment: 'blacklister', values?: undefined): string
    encodeFunctionData(functionFragment: 'currency', values?: undefined): string
    encodeFunctionData(functionFragment: 'decimals', values?: undefined): string
    encodeFunctionData(functionFragment: 'fiatTokenOwner', values?: undefined): string
    encodeFunctionData(functionFragment: 'masterMinter', values?: undefined): string
    encodeFunctionData(functionFragment: 'name', values?: undefined): string
    encodeFunctionData(functionFragment: 'owner', values?: undefined): string
    encodeFunctionData(functionFragment: 'pauser', values?: undefined): string
    encodeFunctionData(functionFragment: 'proxy', values?: undefined): string
    encodeFunctionData(functionFragment: 'symbol', values?: undefined): string
    encodeFunctionData(functionFragment: 'tearDown', values?: undefined): string
    encodeFunctionData(
        functionFragment: 'transferFrom',
        values: [PromiseOrValue<string>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
    ): string
    encodeFunctionData(functionFragment: 'transferOwnership', values: [PromiseOrValue<string>]): string

    decodeFunctionResult(functionFragment: 'balanceOf', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'blacklister', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'currency', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'decimals', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'fiatTokenOwner', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'masterMinter', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'name', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'owner', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'pauser', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'proxy', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'symbol', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'tearDown', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'transferFrom', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'transferOwnership', data: BytesLike): Result

    events: {
        'OwnershipTransferred(address,address)': EventFragment
    }

    getEvent(nameOrSignatureOrTopic: 'OwnershipTransferred'): EventFragment
}

export interface OwnershipTransferredEventObject {
    previousOwner: string
    newOwner: string
}
export type OwnershipTransferredEvent = TypedEvent<[string, string], OwnershipTransferredEventObject>

export type OwnershipTransferredEventFilter = TypedEventFilter<OwnershipTransferredEvent>

export interface V2UpgraderHelper extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: V2UpgraderHelperInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<[BigNumber]>

        blacklister(overrides?: CallOverrides): Promise<[string]>

        currency(overrides?: CallOverrides): Promise<[string]>

        decimals(overrides?: CallOverrides): Promise<[number]>

        fiatTokenOwner(overrides?: CallOverrides): Promise<[string]>

        masterMinter(overrides?: CallOverrides): Promise<[string]>

        name(overrides?: CallOverrides): Promise<[string]>

        owner(overrides?: CallOverrides): Promise<[string]>

        pauser(overrides?: CallOverrides): Promise<[string]>

        proxy(overrides?: CallOverrides): Promise<[string]>

        symbol(overrides?: CallOverrides): Promise<[string]>

        tearDown(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

        transferFrom(
            from: PromiseOrValue<string>,
            to: PromiseOrValue<string>,
            value: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        transferOwnership(
            newOwner: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

    blacklister(overrides?: CallOverrides): Promise<string>

    currency(overrides?: CallOverrides): Promise<string>

    decimals(overrides?: CallOverrides): Promise<number>

    fiatTokenOwner(overrides?: CallOverrides): Promise<string>

    masterMinter(overrides?: CallOverrides): Promise<string>

    name(overrides?: CallOverrides): Promise<string>

    owner(overrides?: CallOverrides): Promise<string>

    pauser(overrides?: CallOverrides): Promise<string>

    proxy(overrides?: CallOverrides): Promise<string>

    symbol(overrides?: CallOverrides): Promise<string>

    tearDown(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ContractTransaction>

    transferFrom(
        from: PromiseOrValue<string>,
        to: PromiseOrValue<string>,
        value: PromiseOrValue<BigNumberish>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    transferOwnership(
        newOwner: PromiseOrValue<string>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

        blacklister(overrides?: CallOverrides): Promise<string>

        currency(overrides?: CallOverrides): Promise<string>

        decimals(overrides?: CallOverrides): Promise<number>

        fiatTokenOwner(overrides?: CallOverrides): Promise<string>

        masterMinter(overrides?: CallOverrides): Promise<string>

        name(overrides?: CallOverrides): Promise<string>

        owner(overrides?: CallOverrides): Promise<string>

        pauser(overrides?: CallOverrides): Promise<string>

        proxy(overrides?: CallOverrides): Promise<string>

        symbol(overrides?: CallOverrides): Promise<string>

        tearDown(overrides?: CallOverrides): Promise<void>

        transferFrom(
            from: PromiseOrValue<string>,
            to: PromiseOrValue<string>,
            value: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<boolean>

        transferOwnership(newOwner: PromiseOrValue<string>, overrides?: CallOverrides): Promise<void>
    }

    filters: {
        'OwnershipTransferred(address,address)'(previousOwner?: null, newOwner?: null): OwnershipTransferredEventFilter
        OwnershipTransferred(previousOwner?: null, newOwner?: null): OwnershipTransferredEventFilter
    }

    estimateGas: {
        balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<BigNumber>

        blacklister(overrides?: CallOverrides): Promise<BigNumber>

        currency(overrides?: CallOverrides): Promise<BigNumber>

        decimals(overrides?: CallOverrides): Promise<BigNumber>

        fiatTokenOwner(overrides?: CallOverrides): Promise<BigNumber>

        masterMinter(overrides?: CallOverrides): Promise<BigNumber>

        name(overrides?: CallOverrides): Promise<BigNumber>

        owner(overrides?: CallOverrides): Promise<BigNumber>

        pauser(overrides?: CallOverrides): Promise<BigNumber>

        proxy(overrides?: CallOverrides): Promise<BigNumber>

        symbol(overrides?: CallOverrides): Promise<BigNumber>

        tearDown(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<BigNumber>

        transferFrom(
            from: PromiseOrValue<string>,
            to: PromiseOrValue<string>,
            value: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        transferOwnership(
            newOwner: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        balanceOf(account: PromiseOrValue<string>, overrides?: CallOverrides): Promise<PopulatedTransaction>

        blacklister(overrides?: CallOverrides): Promise<PopulatedTransaction>

        currency(overrides?: CallOverrides): Promise<PopulatedTransaction>

        decimals(overrides?: CallOverrides): Promise<PopulatedTransaction>

        fiatTokenOwner(overrides?: CallOverrides): Promise<PopulatedTransaction>

        masterMinter(overrides?: CallOverrides): Promise<PopulatedTransaction>

        name(overrides?: CallOverrides): Promise<PopulatedTransaction>

        owner(overrides?: CallOverrides): Promise<PopulatedTransaction>

        pauser(overrides?: CallOverrides): Promise<PopulatedTransaction>

        proxy(overrides?: CallOverrides): Promise<PopulatedTransaction>

        symbol(overrides?: CallOverrides): Promise<PopulatedTransaction>

        tearDown(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<PopulatedTransaction>

        transferFrom(
            from: PromiseOrValue<string>,
            to: PromiseOrValue<string>,
            value: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        transferOwnership(
            newOwner: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
