/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import type { Provider, TransactionRequest } from '@ethersproject/providers'
import type { PromiseOrValue } from '../../../common'
import type { ReadCmdCodecV1, ReadCmdCodecV1Interface } from '../../../uln/libs/ReadCmdCodecV1'

const _abi = [
    {
        inputs: [],
        name: 'InvalidCmd',
        type: 'error',
    },
    {
        inputs: [],
        name: 'InvalidType',
        type: 'error',
    },
    {
        inputs: [],
        name: 'InvalidVersion',
        type: 'error',
    },
] as const

const _bytecode =
    '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea2646970667358221220709cee864a4032dee588b31c4053db7ee2a1c853a54322335922173d38b3c49964736f6c63430008160033'

type ReadCmdCodecV1ConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (xs: ReadCmdCodecV1ConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
    xs.length > 1

export class ReadCmdCodecV1__factory extends ContractFactory {
    constructor(...args: ReadCmdCodecV1ConstructorParams) {
        if (isSuperArgs(args)) {
            super(...args)
        } else {
            super(_abi, _bytecode, args[0])
        }
    }

    override deploy(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<ReadCmdCodecV1> {
        return super.deploy(overrides || {}) as Promise<ReadCmdCodecV1>
    }
    override getDeployTransaction(overrides?: Overrides & { from?: PromiseOrValue<string> }): TransactionRequest {
        return super.getDeployTransaction(overrides || {})
    }
    override attach(address: string): ReadCmdCodecV1 {
        return super.attach(address) as ReadCmdCodecV1
    }
    override connect(signer: Signer): ReadCmdCodecV1__factory {
        return super.connect(signer) as ReadCmdCodecV1__factory
    }

    static readonly bytecode = _bytecode
    static readonly abi = _abi
    static createInterface(): ReadCmdCodecV1Interface {
        return new utils.Interface(_abi) as ReadCmdCodecV1Interface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): ReadCmdCodecV1 {
        return new Contract(address, _abi, signerOrProvider) as ReadCmdCodecV1
    }
}
