/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../common'

export interface TreasuryFeeHandlerInterface extends utils.Interface {
    functions: {
        'endpoint()': FunctionFragment
        'payFee(address,address,uint256,uint256,address)': FunctionFragment
    }

    getFunction(nameOrSignatureOrTopic: 'endpoint' | 'payFee'): FunctionFragment

    encodeFunctionData(functionFragment: 'endpoint', values?: undefined): string
    encodeFunctionData(
        functionFragment: 'payFee',
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<string>,
        ]
    ): string

    decodeFunctionResult(functionFragment: 'endpoint', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'payFee', data: BytesLike): Result

    events: {}
}

export interface TreasuryFeeHandler extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: TreasuryFeeHandlerInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        endpoint(overrides?: CallOverrides): Promise<[string]>

        payFee(
            _lzToken: PromiseOrValue<string>,
            _sender: PromiseOrValue<string>,
            _required: PromiseOrValue<BigNumberish>,
            _supplied: PromiseOrValue<BigNumberish>,
            _treasury: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    endpoint(overrides?: CallOverrides): Promise<string>

    payFee(
        _lzToken: PromiseOrValue<string>,
        _sender: PromiseOrValue<string>,
        _required: PromiseOrValue<BigNumberish>,
        _supplied: PromiseOrValue<BigNumberish>,
        _treasury: PromiseOrValue<string>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        endpoint(overrides?: CallOverrides): Promise<string>

        payFee(
            _lzToken: PromiseOrValue<string>,
            _sender: PromiseOrValue<string>,
            _required: PromiseOrValue<BigNumberish>,
            _supplied: PromiseOrValue<BigNumberish>,
            _treasury: PromiseOrValue<string>,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {}

    estimateGas: {
        endpoint(overrides?: CallOverrides): Promise<BigNumber>

        payFee(
            _lzToken: PromiseOrValue<string>,
            _sender: PromiseOrValue<string>,
            _required: PromiseOrValue<BigNumberish>,
            _supplied: PromiseOrValue<BigNumberish>,
            _treasury: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        endpoint(overrides?: CallOverrides): Promise<PopulatedTransaction>

        payFee(
            _lzToken: PromiseOrValue<string>,
            _sender: PromiseOrValue<string>,
            _required: PromiseOrValue<BigNumberish>,
            _supplied: PromiseOrValue<BigNumberish>,
            _treasury: PromiseOrValue<string>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
