/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Signer, utils } from 'ethers'
import type { Provider } from '@ethersproject/providers'
import type { IOAppComputerReduce, IOAppComputerReduceInterface } from '../../../oapp/interfaces/IOAppComputerReduce'

const _abi = [
    {
        inputs: [
            {
                internalType: 'bytes',
                name: '_cmd',
                type: 'bytes',
            },
            {
                internalType: 'bytes[]',
                name: '_responses',
                type: 'bytes[]',
            },
        ],
        name: 'lzReduce',
        outputs: [
            {
                internalType: 'bytes',
                name: '',
                type: 'bytes',
            },
        ],
        stateMutability: 'view',
        type: 'function',
    },
] as const

export class IOAppComputerReduce__factory {
    static readonly abi = _abi
    static createInterface(): IOAppComputerReduceInterface {
        return new utils.Interface(_abi) as IOAppComputerReduceInterface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): IOAppComputerReduce {
        return new Contract(address, _abi, signerOrProvider) as IOAppComputerReduce
    }
}
