/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../../../common'

export interface ILayerZeroReceiveLibraryInterface extends utils.Interface {
    functions: {
        'getConfig(uint16,address,uint256)': FunctionFragment
        'setConfig(uint16,address,uint256,bytes)': FunctionFragment
    }

    getFunction(nameOrSignatureOrTopic: 'getConfig' | 'setConfig'): FunctionFragment

    encodeFunctionData(
        functionFragment: 'getConfig',
        values: [PromiseOrValue<BigNumberish>, PromiseOrValue<string>, PromiseOrValue<BigNumberish>]
    ): string
    encodeFunctionData(
        functionFragment: 'setConfig',
        values: [
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>,
        ]
    ): string

    decodeFunctionResult(functionFragment: 'getConfig', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'setConfig', data: BytesLike): Result

    events: {}
}

export interface ILayerZeroReceiveLibrary extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: ILayerZeroReceiveLibraryInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        getConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<[string]>

        setConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            _config: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    getConfig(
        _chainId: PromiseOrValue<BigNumberish>,
        _userApplication: PromiseOrValue<string>,
        _configType: PromiseOrValue<BigNumberish>,
        overrides?: CallOverrides
    ): Promise<string>

    setConfig(
        _chainId: PromiseOrValue<BigNumberish>,
        _userApplication: PromiseOrValue<string>,
        _configType: PromiseOrValue<BigNumberish>,
        _config: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        getConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<string>

        setConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            _config: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {}

    estimateGas: {
        getConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<BigNumber>

        setConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            _config: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        getConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<PopulatedTransaction>

        setConfig(
            _chainId: PromiseOrValue<BigNumberish>,
            _userApplication: PromiseOrValue<string>,
            _configType: PromiseOrValue<BigNumberish>,
            _config: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
