/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import type { Provider, TransactionRequest } from '@ethersproject/providers'
import type { PromiseOrValue } from '../../../../../common'
import type {
    DVNAdapterMessageCodec,
    DVNAdapterMessageCodecInterface,
} from '../../../../../uln/dvn/adapters/libs/DVNAdapterMessageCodec'

const _abi = [
    {
        inputs: [],
        name: 'DVNAdapter_InvalidMessageSize',
        type: 'error',
    },
] as const

const _bytecode =
    '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212203902c7fdc7724c29f89c78d6c0d147c94d7df95f2a18e9a8f68a81a01c2129fe64736f6c63430008160033'

type DVNAdapterMessageCodecConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (
    xs: DVNAdapterMessageCodecConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1

export class DVNAdapterMessageCodec__factory extends ContractFactory {
    constructor(...args: DVNAdapterMessageCodecConstructorParams) {
        if (isSuperArgs(args)) {
            super(...args)
        } else {
            super(_abi, _bytecode, args[0])
        }
    }

    override deploy(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<DVNAdapterMessageCodec> {
        return super.deploy(overrides || {}) as Promise<DVNAdapterMessageCodec>
    }
    override getDeployTransaction(overrides?: Overrides & { from?: PromiseOrValue<string> }): TransactionRequest {
        return super.getDeployTransaction(overrides || {})
    }
    override attach(address: string): DVNAdapterMessageCodec {
        return super.attach(address) as DVNAdapterMessageCodec
    }
    override connect(signer: Signer): DVNAdapterMessageCodec__factory {
        return super.connect(signer) as DVNAdapterMessageCodec__factory
    }

    static readonly bytecode = _bytecode
    static readonly abi = _abi
    static createInterface(): DVNAdapterMessageCodecInterface {
        return new utils.Interface(_abi) as DVNAdapterMessageCodecInterface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): DVNAdapterMessageCodec {
        return new Contract(address, _abi, signerOrProvider) as DVNAdapterMessageCodec
    }
}
