[profile.default]
src = "src"
out = "out"
cache_path = "cache/foundry"
verbosity = 3
optimizer = true
optimizer_runs = 5000

libs = ['node_modules/@layerzerolabs/toolbox-foundry/lib', 'node_modules']

remappings = [
    # Due to a misconfiguration of solidity-bytes-utils, an outdated version
    # of forge-std is being dragged in
    # 
    # To remedy this, we'll remap the ds-test and forge-std imports to our own versions
    'ds-test/=node_modules/@layerzerolabs/toolbox-foundry/lib/ds-test',
    'forge-std/=node_modules/@layerzerolabs/toolbox-foundry/lib/forge-std',
    'hardhat-deploy/=node_modules/hardhat-deploy/',
    'solmate/=node_modules/solmate/',
    '@ensdomains/=node_modules/@ensdomains/',
    '@layerzerolabs/=node_modules/@layerzerolabs/',
    '@openzeppelin/=node_modules/@openzeppelin/',
    '@uniswap/=node_modules/@uniswap/',
]

gas_reports = [
    "StargateOFT", 
    "StargatePool", "StargatePoolMigratable", "StargatePoolNative",
    "FeeLibV1",
    "CreditMessaging", "TokenMessaging",
    "StargateMultiRewarder", "StargateStaking",
    "StargateZapperV1",
    "StargateOFTUSDC", "StargatePoolUSDC", "FiatTokenV2_2",
    "StargateOFTEURC", "StargatePoolEURC",
    "LPToken", "OFTTokenERC20", "OFTTokenERC20Upgradeable"
]

#viaIR = true
#
#[profile.default.optimizer_details.yulDetails]
#optimizerSteps = ''

# fuzz, invariant
[fuzz]
runs = 1000

[invariant]
call_override = false # Override calls
runs = 1              # The number of times to run the invariant tests
depth = 5000          # The number of calls to make in the invariant tests

[profile.no_revert.invariant]
fail_on_revert = true # Fail the test if the contract reverts

[profile.allow_revert.invariant]
fail_on_revert = false # Fail the test if the contract reverts

# These are here for testing purposes since zapper tests require stable forking
[rpc_endpoints]
ethereum_mainnet = "${RPC_URL_ETHEREUM_MAINNET}"
