/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../common'

export type OriginStruct = {
    srcEid: PromiseOrValue<BigNumberish>
    sender: PromiseOrValue<BytesLike>
    nonce: PromiseOrValue<BigNumberish>
}

export type OriginStructOutput = [number, string, BigNumber] & {
    srcEid: number
    sender: string
    nonce: BigNumber
}

export interface ITokenMessagingHandlerInterface extends utils.Interface {
    functions: {
        'receiveTokenBus((uint32,bytes32,uint64),bytes32,uint8,address,uint64)': FunctionFragment
        'receiveTokenTaxi((uint32,bytes32,uint64),bytes32,address,uint64,bytes)': FunctionFragment
    }

    getFunction(nameOrSignatureOrTopic: 'receiveTokenBus' | 'receiveTokenTaxi'): FunctionFragment

    encodeFunctionData(
        functionFragment: 'receiveTokenBus',
        values: [
            OriginStruct,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
        ]
    ): string
    encodeFunctionData(
        functionFragment: 'receiveTokenTaxi',
        values: [
            OriginStruct,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<string>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>,
        ]
    ): string

    decodeFunctionResult(functionFragment: 'receiveTokenBus', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'receiveTokenTaxi', data: BytesLike): Result

    events: {}
}

export interface ITokenMessagingHandler extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: ITokenMessagingHandlerInterface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        receiveTokenBus(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _seatNumber: PromiseOrValue<BigNumberish>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        receiveTokenTaxi(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            _composeMsg: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    receiveTokenBus(
        _origin: OriginStruct,
        _guid: PromiseOrValue<BytesLike>,
        _seatNumber: PromiseOrValue<BigNumberish>,
        _receiver: PromiseOrValue<string>,
        _amountSD: PromiseOrValue<BigNumberish>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    receiveTokenTaxi(
        _origin: OriginStruct,
        _guid: PromiseOrValue<BytesLike>,
        _receiver: PromiseOrValue<string>,
        _amountSD: PromiseOrValue<BigNumberish>,
        _composeMsg: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        receiveTokenBus(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _seatNumber: PromiseOrValue<BigNumberish>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            overrides?: CallOverrides
        ): Promise<void>

        receiveTokenTaxi(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            _composeMsg: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {}

    estimateGas: {
        receiveTokenBus(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _seatNumber: PromiseOrValue<BigNumberish>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        receiveTokenTaxi(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            _composeMsg: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        receiveTokenBus(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _seatNumber: PromiseOrValue<BigNumberish>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        receiveTokenTaxi(
            _origin: OriginStruct,
            _guid: PromiseOrValue<BytesLike>,
            _receiver: PromiseOrValue<string>,
            _amountSD: PromiseOrValue<BigNumberish>,
            _composeMsg: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
