name: Setup environment
description: Setup dependencies required to build & test the repository
runs:
  using: "composite"
  steps:
    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@908c540300062bd5a7e473851cdb4282204cee09 # v1
      with:
        version: v0.3.0

    - uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4
      name: Install pnpm
      with:
        run_install: false
