chains:
  #  - name: template-chain
  #   eid: TEMPLATE_V2_MAINNET
  #   token_messaging: true  # if the chain supports token messaging
  #   credit_messaging: true # if the chain supports credit messaging
  #   tokens:  # list of tokens supported by the chain and each token has a type (native, pool, oft)
  #     eth:
  #       type: native/pool/oft
  #   rewarder:
  #     tokens:  # list of reward tokens supported by the chain and each reward token's allocation
  #       arb:
  #         allocation:
  #           eth: 10
  #           usdc: 10
  #           usdt: 10
  #       stg:
  #         allocation:
  #           eth: 10
  #           usdc: 10
  #           usdt: 10
  #   staking:  # list of tokens that support staking in the chain
  #     tokens:
  #       eth: true
  #       usdc: true
  #       usdt: true
  #   treasurer:  # list of tokens that support the treasurer in the chain
  #       eth: true
  #       usdt: true
  #       usdc: true
  #   usdc_admin: true  # if the chain should configure usdc admin

  - name: abstract-mainnet
    eid: ABSTRACT_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: oft
      usdt:
        type: oft
    rewarder:
      tokens:
        eth:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: ape-mainnet
    eid: APE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: arbitrum-mainnet
    eid: ARBITRUM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        arb:
          allocation:
            eth: 6000
            usdc: 2500
            usdt: 1500
        stg:
          allocation:
            eth: 6000
            usdc: 2500
            usdt: 1500
    staking:
      tokens:
        eth: true
        usdc: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: astar-mainnet
    eid: ASTAR_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: aurora-mainnet
    eid: AURORA_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: pool
    rewarder:
      tokens:
        aurora:
          allocation:
            usdc: 10000
    staking:
      tokens:
        usdc: true
    treasurer:
      tokens:
        usdc: true

  - name: avalanche-mainnet
    eid: AVALANCHE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            usdc: 5000
            usdt: 5000
    staking:
      tokens:
        usdc: true
        usdt: true
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: base-mainnet
    eid: BASE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            eth: 6500
            usdc: 3500
    staking:
      tokens:
        eth: true
        usdc: true
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: bera-mainnet
    eid: BERA_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: blast-mainnet
    eid: BLAST_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: bsc-mainnet
    eid: BSC_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            usdc: 1000
            usdt: 9000
    staking:
      tokens:
        usdc: true
        usdt: true
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: codex-mainnet
    eid: CODEX_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
    treasurer:
      tokens:
        usdc: true

  - name: coredao-mainnet
    eid: COREDAO_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        core:
          allocation:
            usdc: 5000
            usdt: 5000
    staking:
      tokens:
        usdc: true
        usdt: true
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: cronosevm-mainnet
    eid: CRONOSEVM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: cronoszkevm-mainnet
    eid: CRONOSZKEVM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: pool
      usdc:
        type: pool
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: degen-mainnet
    eid: DEGEN_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  # ! ebi is shutdown
  # - name: ebi-mainnet
  #   eid: EBI_V2_MAINNET
  #   token_messaging: true
  #   credit_messaging: true
  #   tokens:
  #     usdt:
  #       type: oft
  #   treasurer:
  #     tokens:
  #       usdt: true

  - name: ethereum-mainnet
    eid: ETHEREUM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      meth:
        type: pool
      metis:
        type: pool
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            eth: 4220
            usdc: 3381
            usdt: 2399
    staking:
      tokens:
        eth: true
        usdc: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        meth: true
        metis: true
        usdt: true
        usdc: true

  - name: etherlink-mainnet
    eid: ETHERLINK_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: fantom-mainnet
    eid: FANTOM_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: flare-mainnet
    eid: FLARE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: flow-mainnet
    eid: FLOW_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: fraxtal-mainnet
    eid: FRAXTAL_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: fuse-mainnet
    eid: FUSE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: glue-mainnet
    eid: GLUE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: gnosis-mainnet
    eid: GNOSIS_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: pool
      usdc:
        type: pool
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: goat-mainnet
    eid: GOAT_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: gravity-mainnet
    eid: GRAVITY_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: hemi-mainnet
    eid: HEMI_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: oft
      usdt:
        type: oft
    rewarder:
      tokens:
        weth:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: ink-mainnet
    eid: INK_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
    treasurer:
      tokens:
        usdc: true

  - name: iota-mainnet
    eid: IOTA_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: islander-mainnet
    eid: ISLANDER_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: kava-mainnet
    eid: KAVA_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdt:
        type: pool
    rewarder:
      tokens:
        wkava:
          allocation:
            usdt: 10000
    staking:
      tokens:
        usdt: true
    treasurer:
      tokens:
        usdt: true

  - name: klaytn-mainnet
    eid: KLAYTN_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: lightlink-mainnet
    eid: LIGHTLINK_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: oft
      usdt:
        type: oft
    rewarder:
      tokens:
        lle:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: manta-mainnet
    eid: MANTA_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
    rewarder:
      tokens:
        manta:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true

  - name: mantle-mainnet
    eid: MANTLE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: pool
      meth:
        type: pool
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            eth: 7000
            usdc: 1500
            usdt: 1500
    staking:
      tokens:
        eth: true
        usdc: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        meth: true
        usdt: true
        usdc: true

  - name: metis-mainnet
    eid: METIS_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      metis:
        type: pool
      eth:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        metis:
          allocation:
            eth: 5625
            usdt: 4375
    staking:
      tokens:
        eth: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        metis: true
        usdt: true

  - name: mode-mainnet
    eid: MODE_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: moonbeam-mainnet
    eid: MOONBEAM_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: moonriver-mainnet
    eid: MOONRIVER_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: opbnb-mainnet
    eid: OPBNB_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: optimism-mainnet
    eid: OPTIMISM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        op:
          allocation:
            eth: 6000
            usdc: 1500
            usdt: 2500
        stg:
          allocation:
            eth: 6000
            usdc: 1500
            usdt: 2500
    staking:
      tokens:
        eth: true
        usdc: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: peaq-mainnet
    eid: PEAQ_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true
    usdc_admin: true

  - name: plume-mainnet
    eid: PLUME_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: plumephoenix-mainnet
    eid: PLUMEPHOENIX_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: polygon-mainnet
    eid: POLYGON_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            usdc: 5959
            usdt: 4041
    staking:
      tokens:
        usdc: true
        usdt: true
    treasurer:
      tokens:
        usdt: true
        usdc: true

  - name: rarible-mainnet
    eid: RARIBLE_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        usdt: true
        usdc: true
    usdc_admin: true

  - name: rootstock-mainnet
    eid: ROOTSTOCK_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: scroll-mainnet
    eid: SCROLL_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: pool
    rewarder:
      tokens:
        stg:
          allocation:
            eth: 7000
            usdc: 3000
    staking:
      tokens:
        eth: true
        usdc: true
    treasurer:
      tokens:
        eth: true
        usdc: true

  - name: sei-mainnet
    eid: SEI_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: pool
      usdt:
        type: pool
    rewarder:
      tokens:
        sei:
          allocation:
            usdc: 5000
            usdt: 5000
    staking:
      tokens:
        usdc: true
        usdt: true
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: shimmer-mainnet
    eid: SHIMMER_V2_MAINNET
    token_messaging: false
    credit_messaging: false

  - name: soneium-mainnet
    eid: SONEIUM_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
      usdc:
        type: pool
    rewarder:
      tokens:
        weth:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true
        usdc: true
    treasurer:
      tokens:
        eth: true
        usdc: true

  # - name: sonic-mainnet
  #   eid: SONIC_V2_MAINNET
  #   token_messaging: true
  #   credit_messaging: true
  #   tokens:
  #     usdc:
  #       type: pool
  #   rewarder:
  #     tokens:
  #       s:
  #         allocation:
  #           usdc: 10000
  #   staking:
  #     tokens:
  #       usdc: true
  #   treasurer:
  #     tokens:
  #       usdc: true

  - name: story-mainnet
    eid: STORY_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: superposition-mainnet
    eid: SUPERPOSITION_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
    treasurer:
      tokens:
        usdc: true

  - name: taiko-mainnet
    eid: TAIKO_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        usdt: true
        usdc: true
    usdc_admin: true

  - name: telos-mainnet
    eid: TELOS_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: oft
      usdc:
        type: oft
      usdt:
        type: oft
    treasurer:
      tokens:
        eth: true
        usdt: true
        usdc: true

  - name: unichain-mainnet
    eid: UNICHAIN_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
    treasurer:
      tokens:
        eth: true

  - name: xchain-mainnet
    eid: XCHAIN_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      usdc:
        type: oft
    treasurer:
      tokens:
        usdc: true
    usdc_admin: true

  # - name: zkatana-mainnet
  #   eid: ZKATANA_V2_MAINNET
  #   token_messaging: false
  #   credit_messaging: false

  - name: zkconsensys-mainnet
    eid: ZKCONSENSYS_V2_MAINNET
    token_messaging: true
    credit_messaging: true
    tokens:
      eth:
        type: native
    rewarder:
      tokens:
        stg:
          allocation:
            eth: 10000
    staking:
      tokens:
        eth: true
    treasurer:
      tokens:
        eth: true

  - name: zkpolygon-mainnet
    eid: ZKPOLYGON_V2_MAINNET
    token_messaging: false
    credit_messaging: false
