/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { IReceiveUln301 } from './IReceiveUln301'
export type { ReceiveUln301View } from './ReceiveUln301View'
