/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
    BaseContract,
    BigNumber,
    BigNumberish,
    BytesLike,
    CallOverrides,
    ContractTransaction,
    Overrides,
    PayableOverrides,
    PopulatedTransaction,
    Signer,
    utils,
} from 'ethers'
import type { FunctionFragment, Result } from '@ethersproject/abi'
import type { Listener, Provider } from '@ethersproject/providers'
import type { TypedEventFilter, TypedEvent, TypedListener, OnEvent, PromiseOrValue } from '../common'

export type OriginStruct = {
    srcEid: PromiseOrValue<BigNumberish>
    sender: PromiseOrValue<BytesLike>
    nonce: PromiseOrValue<BigNumberish>
}

export type OriginStructOutput = [number, string, BigNumber] & {
    srcEid: number
    sender: string
    nonce: BigNumber
}

export interface ILayerZeroEndpointV2Interface extends utils.Interface {
    functions: {
        'eid()': FunctionFragment
        'lzCompose(address,address,bytes32,uint16,bytes,bytes)': FunctionFragment
        'lzComposeAlert(address,address,bytes32,uint16,uint256,uint256,bytes,bytes,bytes)': FunctionFragment
        'lzReceive((uint32,bytes32,uint64),address,bytes32,bytes,bytes)': FunctionFragment
        'lzReceiveAlert((uint32,bytes32,uint64),address,bytes32,uint256,uint256,bytes,bytes,bytes)': FunctionFragment
    }

    getFunction(
        nameOrSignatureOrTopic: 'eid' | 'lzCompose' | 'lzComposeAlert' | 'lzReceive' | 'lzReceiveAlert'
    ): FunctionFragment

    encodeFunctionData(functionFragment: 'eid', values?: undefined): string
    encodeFunctionData(
        functionFragment: 'lzCompose',
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
        ]
    ): string
    encodeFunctionData(
        functionFragment: 'lzComposeAlert',
        values: [
            PromiseOrValue<string>,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
        ]
    ): string
    encodeFunctionData(
        functionFragment: 'lzReceive',
        values: [
            OriginStruct,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
        ]
    ): string
    encodeFunctionData(
        functionFragment: 'lzReceiveAlert',
        values: [
            OriginStruct,
            PromiseOrValue<string>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BigNumberish>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
            PromiseOrValue<BytesLike>,
        ]
    ): string

    decodeFunctionResult(functionFragment: 'eid', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'lzCompose', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'lzComposeAlert', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'lzReceive', data: BytesLike): Result
    decodeFunctionResult(functionFragment: 'lzReceiveAlert', data: BytesLike): Result

    events: {}
}

export interface ILayerZeroEndpointV2 extends BaseContract {
    connect(signerOrProvider: Signer | Provider | string): this
    attach(addressOrName: string): this
    deployed(): Promise<this>

    interface: ILayerZeroEndpointV2Interface

    queryFilter<TEvent extends TypedEvent>(
        event: TypedEventFilter<TEvent>,
        fromBlockOrBlockhash?: string | number | undefined,
        toBlock?: string | number | undefined
    ): Promise<Array<TEvent>>

    listeners<TEvent extends TypedEvent>(eventFilter?: TypedEventFilter<TEvent>): Array<TypedListener<TEvent>>
    listeners(eventName?: string): Array<Listener>
    removeAllListeners<TEvent extends TypedEvent>(eventFilter: TypedEventFilter<TEvent>): this
    removeAllListeners(eventName?: string): this
    off: OnEvent<this>
    on: OnEvent<this>
    once: OnEvent<this>
    removeListener: OnEvent<this>

    functions: {
        eid(overrides?: CallOverrides): Promise<[number]>

        lzCompose(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        lzComposeAlert(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        lzReceive(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>

        lzReceiveAlert(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<ContractTransaction>
    }

    eid(overrides?: CallOverrides): Promise<number>

    lzCompose(
        _from: PromiseOrValue<string>,
        _to: PromiseOrValue<string>,
        _guid: PromiseOrValue<BytesLike>,
        _index: PromiseOrValue<BigNumberish>,
        _message: PromiseOrValue<BytesLike>,
        _extraData: PromiseOrValue<BytesLike>,
        overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    lzComposeAlert(
        _from: PromiseOrValue<string>,
        _to: PromiseOrValue<string>,
        _guid: PromiseOrValue<BytesLike>,
        _index: PromiseOrValue<BigNumberish>,
        _gas: PromiseOrValue<BigNumberish>,
        _value: PromiseOrValue<BigNumberish>,
        _message: PromiseOrValue<BytesLike>,
        _extraData: PromiseOrValue<BytesLike>,
        _reason: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    lzReceive(
        _origin: OriginStruct,
        _receiver: PromiseOrValue<string>,
        _guid: PromiseOrValue<BytesLike>,
        _message: PromiseOrValue<BytesLike>,
        _extraData: PromiseOrValue<BytesLike>,
        overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    lzReceiveAlert(
        _origin: OriginStruct,
        _receiver: PromiseOrValue<string>,
        _guid: PromiseOrValue<BytesLike>,
        _gas: PromiseOrValue<BigNumberish>,
        _value: PromiseOrValue<BigNumberish>,
        _message: PromiseOrValue<BytesLike>,
        _extraData: PromiseOrValue<BytesLike>,
        _reason: PromiseOrValue<BytesLike>,
        overrides?: Overrides & { from?: PromiseOrValue<string> }
    ): Promise<ContractTransaction>

    callStatic: {
        eid(overrides?: CallOverrides): Promise<number>

        lzCompose(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>

        lzComposeAlert(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>

        lzReceive(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>

        lzReceiveAlert(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: CallOverrides
        ): Promise<void>
    }

    filters: {}

    estimateGas: {
        eid(overrides?: CallOverrides): Promise<BigNumber>

        lzCompose(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        lzComposeAlert(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        lzReceive(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>

        lzReceiveAlert(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<BigNumber>
    }

    populateTransaction: {
        eid(overrides?: CallOverrides): Promise<PopulatedTransaction>

        lzCompose(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        lzComposeAlert(
            _from: PromiseOrValue<string>,
            _to: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _index: PromiseOrValue<BigNumberish>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        lzReceive(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            overrides?: PayableOverrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>

        lzReceiveAlert(
            _origin: OriginStruct,
            _receiver: PromiseOrValue<string>,
            _guid: PromiseOrValue<BytesLike>,
            _gas: PromiseOrValue<BigNumberish>,
            _value: PromiseOrValue<BigNumberish>,
            _message: PromiseOrValue<BytesLike>,
            _extraData: PromiseOrValue<BytesLike>,
            _reason: PromiseOrValue<BytesLike>,
            overrides?: Overrides & { from?: PromiseOrValue<string> }
        ): Promise<PopulatedTransaction>
    }
}
