/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from 'ethers'
import type { Provider, TransactionRequest } from '@ethersproject/providers'
import type { PromiseOrValue } from '../../common'
import type { TaxiCodec, TaxiCodecInterface } from '../../libs/TaxiCodec'

const _abi = [
    {
        inputs: [],
        name: 'TaxiCodec_InvalidMessage',
        type: 'error',
    },
] as const

const _bytecode =
    '0x60566037600b82828239805160001a607314602a57634e487b7160e01b600052600060045260246000fd5b30600052607381538281f3fe73000000000000000000000000000000000000000030146080604052600080fdfea26469706673582212207621b58c0efbd032fc5e8ab8889a14ca18008f81891172eb48e4bf435121b4ea64736f6c63430008160033'

type TaxiCodecConstructorParams = [signer?: Signer] | ConstructorParameters<typeof ContractFactory>

const isSuperArgs = (xs: TaxiCodecConstructorParams): xs is ConstructorParameters<typeof ContractFactory> =>
    xs.length > 1

export class TaxiCodec__factory extends ContractFactory {
    constructor(...args: TaxiCodecConstructorParams) {
        if (isSuperArgs(args)) {
            super(...args)
        } else {
            super(_abi, _bytecode, args[0])
        }
    }

    override deploy(overrides?: Overrides & { from?: PromiseOrValue<string> }): Promise<TaxiCodec> {
        return super.deploy(overrides || {}) as Promise<TaxiCodec>
    }
    override getDeployTransaction(overrides?: Overrides & { from?: PromiseOrValue<string> }): TransactionRequest {
        return super.getDeployTransaction(overrides || {})
    }
    override attach(address: string): TaxiCodec {
        return super.attach(address) as TaxiCodec
    }
    override connect(signer: Signer): TaxiCodec__factory {
        return super.connect(signer) as TaxiCodec__factory
    }

    static readonly bytecode = _bytecode
    static readonly abi = _abi
    static createInterface(): TaxiCodecInterface {
        return new utils.Interface(_abi) as TaxiCodecInterface
    }
    static connect(address: string, signerOrProvider: Signer | Provider): TaxiCodec {
        return new Contract(address, _abi, signerOrProvider) as TaxiCodec
    }
}
