name: Offchain Checker
permissions:
  contents: read

on:
  workflow_dispatch:

jobs:
  validate:
    name: Run stg-evm-sdk-v2 validation
    runs-on: ubuntu-latest-4xlarge
    env:
      NPM_TOKEN: ""
      RPC_URL_MAINNET: ${{ secrets.RPC_URL_MAINNET }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Setup pnpm
        uses: pnpm/action-setup@b906affcce14559ad1aafd4ab0e942779e9f58b1 # v4

      - name: Build
        uses: ./.github/workflows/actions/build

      - name: Run offchain validation
        working-directory: packages/stg-evm-sdk-v2
        run: pnpm run validate
